---
- name: db install
  hosts: db
  become: true
  roles:
    - db_ins

- name: bs install
  hosts: bs
  become: true  
  roles:
    - bs_ins

- name: cluster prepare
  hosts: web
  become: true
  roles:
    - web_ins
